### PR TITLE
Parse wide and some irregular forms; fix fas; fix formatting of Dojo examples

### PR DESCRIPTION
**Pull request by dmvianna**
This PR evolved while it was sitting here, so now there's many changes to the `eldoc` support.

1. Parse wide and some irregular forms;
2. Fix **fas** parsing, that was missing;
3. Dojo examples are now correctly formatted;
4. The title is now `<h2>`, as in the markdown.

---
#### Below the original description.

I just noticed that we weren't parsing **fas** (`/`) runes. This PR fixes it.

Additionally, I corrected the docstring formatting according to the standard set by the `checkdoc` command.

### CODE REVIEW

**Comment by dmvianna** [comment]
Also now titles are highlighted, and **dojo** code blocs are correctly rendered (not ignoring `>` and newlines before results):
image

**Comment by dmvianna** [comment]
Now we also parse wide forms and some irregular forms that are amenable to simple **regex** parsing. I guess dealing with `col`, `cencol` and variable length stuff like &grave; would be more convenient in **treesitter** when that's ready.

**Comment by ryjm** [comment]
https://github.com/urbit/hoon-mode.el/blob/da49f6e168aac78cae16e1bbf935084639cd8881/hoon-mode.el#L484

one request, since it messes with tree-sitter output - can you remove this line? otherwise it looks good to me.

also tree-sitter is ready and can be used in conjunction with this. i have a pr up for it https://github.com/urbit-pilled/hoon-ts-mode/pull/1

**Comment by ryjm** [comment]
p.s i use eldoc-hover-box instead, it's a lot nicer and you can see the whole output. probably better for the user to decide in their own config though

**Comment by dmvianna** [comment]
I dropped the echoing of the `thing`. Also added the `cen` irregulars to the dictionary. Many won't be accessible, but it is close enough. Problems for the future.

**Pull request merged**
